language: python
python:
- '3.7'
- 3.7-dev
- '3.8'
- 3.8-dev
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov coverage
install:
- pip install -r requirements.txt
script:
- py.test --cov-report term --cov=digitalarchive
- coverage report --fail-under=100
after_success:
- codecov
deploy:
  provider: pypi
  skip_existing: true
  user: __token__
  password:
    secure: tZmu81/BVRg9a7sg3jqyWBj8BlWkyBMSR8sh2c6pN8njhMGG786Ey5M/Uv1XlbB4AeBVj1k8d/8ODQiHIt5Ah6+Px6GOx5HGuZMA6/9CgPLdr4dWyUvNsw9jflKBdUE6xOb+DEObucmbVvePEOZypNPsUwOtwWZ7QP34clhMDpFWcNx705ArqR1W7dPoceMpzWak4ceENcU1RCSz+IvTmTda8wtfxCqugoiy0rEBohQf5XZFaaRn3it3Zk9POVhHTPvpFlrQaucc0eKGi3z0NbMabmJVho2J2Me9dIWCGFgn1xEMltKUhhTvPSj86Tn6ejjni+LHPO6HWfwxRnfwf1yqN5elK3kypON9ELdPSlisC+BNRkNbby5J0bF5UQSbCyuEKUaeQ5/9baaa8u9BOTkuQzeVUOES0pReww5q6rfEEWEbg9Fs034H4tLaQ4vC0l01AvVcM7PePvREbCGqghskw2E+Y4K5ZW6EHK5UiowcJly3PqWLRCSCZ6ULbCpmfHqKRmUUwTxwvmq8n1yuhBotCkS83HKLw8VlzSvUDNd13p2xtzq6Dh8ZJTpTrJ9XcnZPvHZOB6Go6NzXqWv+QEADfd+QXSMlEoqR1dYUd8pqXC0O/Aep9wHrH/Wx244MTV06XaLayFR5vJKJCRyQHnWnESUpEcfGJA60QkJ2jzk=
  on:
    tags: true
    python: 3.7
