[build-system]
requires = ["flit"]
build-backend = "flit.buildapi"

[tool.flit.metadata]
module = "digitalarchive"
author = "Evan Pikulski"
author-email = "epikulski@gmail.com"
home-page = "https://github.com/epikulski"
classifiers = ["License :: OSI Approved :: MIT License"]

